Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2021-11, with the labels that each got.

#60 Base Settings Added
  .vscode/settings.json
  Examples/BaseSettings_test.py
  RFEM/baseSettings.py
  RFEM/enums.py
  UnitTests/report.html
  UnitTests/test_BaseSettings_test.py
Labels: user story, Medium

#68 Static Analysis Settings
  RFEM/LoadCasesAndCombinations/staticAnalysisSettings.py
  RFEM/enums.py
Labels: Extra Large

#72 Centre of Gravity and Object Information Development
  RFEM/Tools/centreOfGravityAndObjectInfo.py
  RFEM/enums.py
  UnitTests/test_objectInformation.py
Labels: user story, Medium

#73 Frank faulstich solid set loads
  RFEM/BasicObjects/solidSet.py
  RFEM/Loads/solidSetLoad.py
  RFEM/enums.py
  UnitTests/test_SolidLoads.py
Labels: Large

#74 Design Situations Development - DocStrings Update for CEN and DIN National Annex
  RFEM/LoadCasesAndCombinations/designSituation.py
  UnitTests/test_DesignSituations.py
Labels: Small
