Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-08, with the labels that each got.

#150 Heet member local section reduction
  Examples/Cantilever/demo2.py
  RFEM/TypesForSteelDesign/SteelMemberLocalSectionReduction.py
  RFEM/enums.py
  UnitTests/test_SteelMemberLocalSectionReduction.py
Labels: Medium

#151 Heet readme update
  README.md
  img/2Dtruss.gif
  img/PyPI.png
  img/Python.png
  img/RFEM.gif
  img/RFEM.png
  img/RSTAB.png
  img/csharp.png
  img/github-dark.svg
  img/github-light.svg
  img/globe-dark.svg
  img/globe-light.svg
  img/instagram-dark.svg
  img/instagram-light.svg
  img/linkedin-dark.svg
  img/linkedin-light.svg
  img/logo.png
  img/terminal-dark.svg
  img/terminal-light.svg
  img/twitter-dark.svg
  img/twitter-light.svg
  img/youtube-dark.svg
  img/youtube-light.svg
Labels: Medium

#152 Ondrej Michal-result tables
  RFEM/Results/resultTables.py
  RFEM/enums.py
  UnitTests/test_ResultTables.py
Labels: Small

#153 Update README.md
  README.md
Labels: Extra Small
