Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-09, with the labels that each got.

#155 Heet readme update
  README.md
Labels: Extra Small

#159 Update member.py
  RFEM/BasicObjects/member.py
Labels: Small

#166 change: load_parameter allways a list
  RFEM/Loads/memberLoad.py
Labels: Extra Small

#165 created MANIFEST.in
  MANIFEST.in
Labels: Extra Small

#162 created LoadCasesAndCombinations.py
  RFEM/LoadCasesAndCombinations/loadCasesAndCombinations.py
  UnitTests/test_loadCasesAndCombinations.py
Labels: Medium

#170 Heet docstring update
  RFEM/LoadCasesAndCombinations/stabilityAnalysisSettings.py
  RFEM/Loads/memberLoad.py
  RFEM/TypesForSteelDesign/SteelMemberLocalSectionReduction.py
Labels: Extra Small

#169 change: MemberHinge comments for units for passed values
  RFEM/TypesForMembers/memberHinge.py
Labels: Extra Small

#171 change: class typo in word Nonlineartiy-Nonlinearity
  RFEM/TypesForMembers/memberHinge.py
  RFEM/enums.py
  UnitTests/test_typesForMembers.py
Labels: Extra Small

#172 change: DIAGRAM_ENDING_TYPE from TEARING to FAILURE
  RFEM/enums.py
Labels: Extra Small

#173 fix: rows entry for moments
  RFEM/TypesForMembers/memberHinge.py
Labels: Extra Small

#174 add: setup.py - defualt encoding to utf when reading README.md
  setup.py
Labels: Extra Small

#175 Bug - Member hinge diagram case mz , 2 bug fixes
  RFEM/TypesForMembers/memberHinge.py
Labels: Extra Small
