Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-05, with the labels that each got.

#134 Types for Members
  RFEM/TypesForMembers/memberEccentricity.py
  RFEM/TypesForMembers/memberHinge.py
  RFEM/TypesForMembers/memberNonlinearity.py
  RFEM/TypesForMembers/memberResultIntermediatePoints.py
  RFEM/TypesForMembers/memberStiffnessModification.py
  RFEM/TypesForMembers/memberSupport.py
  RFEM/enums.py
  UnitTests/test_typesForMembers.py
Labels: Extra Large

#136 Member Transverse Stiffeners added in Type For Members
  Examples/Cantilever/Demo2.py
  RFEM/TypesForMembers/memberTransverseStiffeners.py
  RFEM/enums.py
  UnitTests/test_typesForMembers.py
Labels: Medium

#133 Truss Generator minor bug fixed
  Examples/TrussGenerator_2D/TrussGenerator.py
Labels: Extra Small

#137 XML Restructuring
  Examples/main.py
  RFEM/BasicObjects/thickness.py
  RFEM/LoadCasesAndCombinations/loadCombination.py
  RFEM/Loads/freeLoad.py
  RFEM/Loads/lineLoad.py
  RFEM/Loads/linesetLoad.py
  RFEM/Loads/memberLoad.py
  RFEM/Loads/membersetload.py
  RFEM/Loads/surfaceLoad.py
  RFEM/Loads/surfacesetload.py
  RFEM/Results/designOverview.py
  RFEM/TypesForLines/lineWeldedJoint.py
  RFEM/TypesForMembers/memberHinge.py
  RFEM/TypesForMembers/memberResultIntermediatePoints.py
  RFEM/TypesForMembers/memberTransverseStiffeners.py
  RFEM/TypesForSteelDesign/steelBoundaryConditions.py
  RFEM/TypesForSteelDesign/steelEffectiveLengths.py
  UnitTests/test_DesignOverview.py
  UnitTests/test_Thickness_Test.py
  UnitTests/test_loadCombination.py
  UnitTests/test_steelBoundaryConditions.py
Labels: Extra Large

#135 Ondrej Michal-special objects update
  RFEM/SpecialObjects/enlargedColumnHead.py
  RFEM/SpecialObjects/intersection.py
  RFEM/SpecialObjects/resultSection.py
  RFEM/SpecialObjects/structureModification.py
  RFEM/SpecialObjects/surfaceContact.py
  RFEM/SpecialObjects/surfaceResultAdjustment.py
  RFEM/TypesForSpecialObjects/surfaceContactType.py
  RFEM/enums.py
  UnitTests/test_SpecialObjects.py
Labels: Extra Large

#138 US-9071: Delete Functions for Objects
  RFEM/BasicObjects/line.py
  RFEM/BasicObjects/lineSet.py
  RFEM/BasicObjects/material.py
  RFEM/BasicObjects/member.py
  RFEM/BasicObjects/memberSet.py
  RFEM/BasicObjects/node.py
  RFEM/BasicObjects/opening.py
  RFEM/BasicObjects/section.py
  RFEM/BasicObjects/solid.py
  RFEM/BasicObjects/solidSet.py
  RFEM/BasicObjects/surface.py
  RFEM/BasicObjects/surfaceSet.py
  RFEM/BasicObjects/thickness.py
  UnitTests/test_basic_objects.py
  UnitTests/test_node.py
  UnitTests/test_solids.py
Labels: Large
