Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-03, with the labels that each got.

#96 Ondrej michal design overview and part list
  RFEM/Reports/partsList.py
  RFEM/Results/designOverview.py
  RFEM/Tools/PlausibilityCheck.py
  RFEM/initModel.py
  UnitTests/test_DesignOverview.py
  UnitTests/test_plausiblityCheck.py
Labels: Medium

#104 Fixed Bugs in Documentation
  docs/.doctrees/environment.pickle
  docs/.doctrees/globalCommands.doctree
  docs/.doctrees/initModel.doctree
  docs/BasicObjects.html
  docs/Imperfections.html
  docs/LoadCasesAndCombinations.html
  docs/Loads.html
  docs/SpecialObjects.html
  docs/TypesForLines.html
  docs/TypesForMembers.html
  docs/TypesForNodes.html
  docs/TypesForSolids.html
  docs/TypesForSpecialObjects.html
  docs/TypesForSurfaces.html
  docs/_sources/globalCommands.rst.txt
  docs/genindex.html
  docs/globalCommands.html
  docs/index.html
  docs/initModel.html
  docs/objects.inv
  docs/py-modindex.html
  docs/searchindex.js
  docs/source/globalCommands.rst
Labels: Extra Large

#98 Effective Lengths - Types for Steel Design
  RFEM/TypesForLines/lineSupport.py
  RFEM/TypesForSteelDesign/steelEffectiveLengths.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/test_steelEffectiveLengths.py
Labels: Large

#108 Ondrej Michal-import export US-7910
  .vscode/settings.json
  Examples/Cantilever/Demo1.py
  RFEM/Calculate/meshSettings.py
  RFEM/ImportExport/exports.py
  RFEM/ImportExport/imports.py
  RFEM/Reports/html.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/src/import_test.saf
  UnitTests/src/import_test.xlsx
  UnitTests/src/import_test.xml
  UnitTests/template.py
  UnitTests/test_BaseSettings_test.py
  UnitTests/test_Export.py
  UnitTests/test_MeshGenerationStatistics.py
  UnitTests/test_ModelCheck.py
  UnitTests/test_SectionDialogue.py
  UnitTests/test_concreteDesign.py
  UnitTests/test_modalAnalysis_test.py
  UnitTests/test_objectInformation.py
  UnitTests/test_stabilitysettings.py
  UnitTests/test_zCalculate.py
Labels: Extra Large

#109 steelBoundaryConditions - TypesForSteelDesign
  RFEM/TypesForSteelDesign/steelBoundaryConditions.py
  RFEM/enums.py
  UnitTests/test_steelBoundaryConditions.py
Labels: Large

#100 add test for initModel insertSpaces
  RFEM/initModel.py
  UnitTests/test_initModel.py
Labels: Extra Small
