Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-11, with the labels that each got.

#187 Removed unused imports
  Examples/TankWebApp/responsiveTank.py
  RFEM/Imperfections/imperfectionCase.py
  RFEM/Tools/ModelCheck.py
  RFEM/TypesForMembers/memberEccentricity.py
  RFEM/TypesForMembers/memberNonlinearity.py
  RFEM/TypesForMembers/memberStiffnessModification.py
  RFEM/TypesForMembers/memberTransverseStiffeners.py
  RFEM/TypesForSteelDesign/steelMemberShearPanel.py
  RFEM/baseSettings.py
  RFEM/initModel.py
  UnitTests/test_LineLoads_Test.py
  UnitTests/test_MeshGenerationStatistics.py
  UnitTests/test_NodalLoad_test.py
  UnitTests/test_RigidLinks.py
  UnitTests/test_SectionDialogue.py
  UnitTests/test_SurfaceSetLoad_test.py
  UnitTests/test_TypesForNodes.py
  UnitTests/test_TypesForSurfaces.py
  UnitTests/test_basic_objects.py
  UnitTests/test_memberDefinableStiffness.py
  UnitTests/test_steelBoundaryConditions.py
  UnitTests/test_steelEffectiveLengths.py
Labels: Extra Small

#189 Björn Steinhagen: getAvailableLoadActionCategoryTypes
  RFEM/LoadCasesAndCombinations/loadCasesAndCombinations.py
  RFEM/dependencies.py
  RFEM/enums.py
  UnitTests/test_availableActionCategories.py
Labels: Extra Small

#191 Steel Design ULS Configurations
  RFEM/SteelDesign/__init__.py
  RFEM/SteelDesign/steelUltimateConfigurations.py
  UnitTests/test_steelDesignUltimateConfigurations.py
Labels: Small

#192 Heet concrete design config
  RFEM/ConcreteDesign/ConcreteServiceabilityConfigurations.py
  RFEM/ConcreteDesign/ConcreteUltimateConfigurations.py
  UnitTests/test_concreteDesignConfig.py
Labels: Medium

#195 OndrejMichal: bug 40607
  RFEM/Tools/GetObjectNumbersByType.py
Labels: bug, Extra Small

#188 Ondrej Michal: TankWebApp update
  .gitignore
  Examples/TankWebApp/export.mtl
  Examples/TankWebApp/export.obj
  Examples/TankWebApp/export/export.mtl
  Examples/TankWebApp/export/export.obj
  Examples/TankWebApp/export/export_0.vtp
  Examples/TankWebApp/responsiveTank.py
  Examples/TankWebApp/tankWebApp.py
  export.obj
Labels: Extra Large
