Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-07, with the labels that each got.

#145 Exception: License Check
  RFEM/initModel.py
Labels: Extra Small

#144 US-9124: Opening Loads
  RFEM/Loads/openingLoad.py
  RFEM/enums.py
  UnitTests/test_loads.py
Labels: Medium

#142 Minor BugFix for Thickness.Layers
  RFEM/BasicObjects/thickness.py
Labels: Extra Small

#143 DesignOverview and SteelEffectiveLengths tests corrected
  RFEM/Calculate/meshSettings.py
  RFEM/Results/designOverview.py
  RFEM/TypesForMembers/memberTransverseStiffeners.py
  RFEM/TypesForSteelDesign/steelEffectiveLengths.py
  RFEM/enums.py
  UnitTests/Examples.py
  UnitTests/test_DesignOverview.py
  UnitTests/test_MeshGenerationStatistics.py
  UnitTests/test_steelEffectiveLengths.py
  UnitTests/test_typesForMembers.py
  UnitTests/test_zCalculate.py
Labels: Extra Small

#146 Unit Tests: Update on Missing or Incomplete Unit Tests
  RFEM/BasicObjects/surface.py
  RFEM/BasicObjects/thickness.py
  RFEM/LoadCasesAndCombinations/spectralAnalysisSettings.py
  RFEM/Loads/lineLoad.py
  RFEM/Loads/memberLoad.py
  RFEM/Loads/membersetload.py
  RFEM/Loads/nodalLoad.py
  RFEM/Loads/surfaceLoad.py
  RFEM/Loads/surfacesetload.py
  RFEM/TypesForSteelDesign/steelMemberRotationalRestraints.py
  RFEM/globalParameter.py
  UnitTests/test_AddOns.py
  UnitTests/test_BaseSettings_test.py
  UnitTests/test_DesignOverview.py
  UnitTests/test_Export.py
  UnitTests/test_Free_Load_Test.py
  UnitTests/test_GlobalParameters_Test.py
  UnitTests/test_LineLoads_Test.py
  UnitTests/test_LoadCases_Test.py
  UnitTests/test_LoadDistributionSurface_Test.py
  UnitTests/test_MemberLoad_test.py
  UnitTests/test_MemberSetLoad_test.py
  UnitTests/test_Member_test.py
  UnitTests/test_MembraneSurface_Test.py
  UnitTests/test_MembraneWithoutTensionSurface_Test.py
  UnitTests/test_NodalLoad_test.py
  UnitTests/test_RigidSurface_Test.py
  UnitTests/test_SectionDialogue.py
  UnitTests/test_SolidLoads.py
  UnitTests/test_SpectralSettings_test.py
  UnitTests/test_StandardSurface_Test.py
  UnitTests/test_SurfaceLoad_test.py
  UnitTests/test_SurfaceSetLoad_test.py
  UnitTests/test_Thickness_Test.py
  UnitTests/test_WithoutThicknessSurface_Test.py
  UnitTests/test_htmlReport.py
  UnitTests/test_loadCombination.py
  UnitTests/test_member_set.py
  UnitTests/test_modalAnalysis_test.py
  UnitTests/test_steelMemberRotationalRestraint.py
  UnitTests/test_typesForLines.py
Labels: Extra Large
