Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-04, with the labels that each got.

#115 Ondrej Michal- bug 22810
  .vscode/settings.json
  RFEM/LoadCasesAndCombinations/designSituation.py
  RFEM/LoadCasesAndCombinations/loadCase.py
  RFEM/enums.py
  UnitTests/test_DesignSituations.py
  UnitTests/test_LoadCases_Test.py
  UnitTests/test_Member_test.py
  UnitTests/test_basic_objects.py
  pylintrc
Labels: Large

#97 Frank faulstich unittest
  UnitTests/test_Export.py
  UnitTests/test_SolidLoads.py
  UnitTests/test_SolidSetLoads.py
  UnitTests/test_basic_objects.py
Labels: Medium

#114 added steelMemberRotationalRestraints
  Examples/Cantilever/Demo1.py
  RFEM/TypesForSteelDesign/steelMemberRotationalRestraints.py
  RFEM/enums.py
  UnitTests/test_steelMemberRotationalRestraint.py
Labels: Medium

#118 Rotated Surface Update
  RFEM/BasicObjects/surface.py
  UnitTests/test_StandardSurface_Test.py
Labels: Extra Small

#119 updated Member Class Line Assignment
  .gitconfig
  .gitmessage
  Examples/Cantilever/Demo1.py
  RFEM/BasicObjects/member.py
Labels: Extra Small

#123 Ondrej Michal: remove suds requests dependency
  RFEM/dependencies.py
  RFEM/initModel.py
  RFEM/suds_requests.py
  UnitTests/test_AddOns.py
  UnitTests/test_suds_requests.py
Labels: Large

#129 update setup.py
  package/setup.py
Labels: Extra Small

#126 DocStrings added to Member Definable Stiffness Class
  RFEM/TypesForMembers/memberDefinableStiffness.py
Labels: documentation, Extra Small

#128 Types for surfaces updated
  RFEM/TypesForSurfaces/surfaceEccentricity.py
  RFEM/TypesForSurfaces/surfaceMeshRefinements.py
  RFEM/TypesForSurfaces/surfaceStiffnessModification.py
  RFEM/TypesForSurfaces/surfaceSupport.py
  RFEM/enums.py
  UnitTests/template.py
  UnitTests/test_RigidLinks.py
  UnitTests/test_SurfaceLoad_test.py
  UnitTests/test_TypesForSurfaces.py
  UnitTests/test_member.py
  UnitTests/test_solids.py
Labels: Large

#131 Update of TypesForSolids
  RFEM/TypesForSolids/solidContact.py
  RFEM/TypesForSolids/solidGas.py
  RFEM/TypesForSolids/solidMeshRefinement.py
  RFEM/enums.py
  UnitTests/test_TypesForSolids.py
Labels: Medium

#132 Automatic Documentation and Packaging
  RFEM/__init__.py
Labels: No Changes

#110 steelMemberShearPanel - Types for Steel Design
  Examples/main.py
  RFEM/Loads/linesetLoad.py
  RFEM/TypesForSteelDesign/steelMemberRotationalRestraints.py
  RFEM/TypesForSteelDesign/steelMemberShearPanel.py
  RFEM/enums.py
  UnitTests/test_steelMemberShearPanel.py
Labels: Large
