Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-12, with the labels that each got.

#196 Heet docstring update
  RFEM/TypesForAluminumDesign/aluminumMemberRotationalRestraints.py
  RFEM/TypesForAluminumDesign/aluminumMemberShearPanel.py
  RFEM/TypesForTimberDesign/timberMemberShearPanel.py
  RFEM/TypesForTimberDesign/timberServiceClass.py
Labels: Extra Small

#197 Update test_NodalLoad_test.py
  UnitTests/test_NodalLoad_test.py
Labels: bug, documentation, Extra Small

#198 Ondrej Michal: Action category types update
  RFEM/LoadCasesAndCombinations/loadCase.py
  RFEM/LoadCasesAndCombinations/loadCasesAndCombinations.py
  RFEM/enums.py
  UnitTests/test_loadCombination.py
Labels: Medium

#200 Action Category Check for LoadCase
  RFEM/LoadCasesAndCombinations/loadCase.py
Labels: Extra Small

#199 US #11367, Add a Save Function
  RFEM/initModel.py
Labels: Extra Small
