Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2022-02, with the labels that each got.

#81 Section Dialogue
  RFEM/Tools/sectionDialogue.py
  UnitTests/src/rsection_test.rsc
  UnitTests/test_SectionDialogue.py
  UnitTests/test_SpectralSettings_test.py
  UnitTests/test_imperfectionCase.py
Labels: Small

#88 FrankFaulstich-Imposed_Line_Deformation
  Examples/test.py
  RFEM/Loads/imposedLineDeformation.py
  UnitTests/test_loads.py
Labels: Small

#92 Load Combination
  RFEM/LoadCasesAndCombinations/loadCombination.py
  RFEM/enums.py
  UnitTests/test_loadCombination.py
Labels: Medium

#65 Concrete Design Input Data
  RFEM/BasicObjects/surface.py
  RFEM/ConcreteDesign/ConcreteServiceabilityConfigurations.py
  RFEM/ConcreteDesign/ConcreteUltimateConfigurations.py
  RFEM/ConcreteDesign/__init__.py
  RFEM/TypesforConcreteDesign/ConcreteDurability.py
  RFEM/TypesforConcreteDesign/ConcreteEffectiveLength.py
  RFEM/TypesforConcreteDesign/ConcreteReinforcementDirections.py
  RFEM/TypesforConcreteDesign/ConcreteSurfaceReinforcements.py
  RFEM/TypesforConcreteDesign/__init__.py
  RFEM/enums.py
  UnitTests/test_LoadDistributionSurface_Test.py
  UnitTests/test_concreteDesign.py
Labels: user story, Extra Large

#89 DocStrings Updates
  RFEM/BasicObjects/bracing.py
  RFEM/BasicObjects/frame.py
  RFEM/BasicObjects/line.py
  RFEM/BasicObjects/lineSet.py
  RFEM/BasicObjects/material.py
  RFEM/BasicObjects/member.py
  RFEM/BasicObjects/memberSet.py
  RFEM/BasicObjects/node.py
  RFEM/BasicObjects/opening.py
  RFEM/BasicObjects/section.py
  RFEM/BasicObjects/solid.py
  RFEM/BasicObjects/solidSet.py
  RFEM/BasicObjects/surface.py
  RFEM/BasicObjects/surfaceSet.py
  RFEM/BasicObjects/thickness.py
  RFEM/Imperfections/imperfectionCase.py
  RFEM/LoadCasesAndCombinations/designSituation.py
  RFEM/LoadCasesAndCombinations/loadCase.py
  RFEM/LoadCasesAndCombinations/resultCombination.py
  RFEM/LoadCasesAndCombinations/spectralAnalysisSettings.py
  RFEM/LoadCasesAndCombinations/stabilityAnalysisSettings.py
  RFEM/LoadCasesAndCombinations/staticAnalysisSettings.py
  RFEM/Loads/freeLoad.py
  RFEM/Loads/lineLoad.py
  RFEM/Loads/memberLoad.py
  UnitTests/test_LoadDistributionSurface_Test.py
Labels: Extra Large

#93 2D Truss Generator Dependency Update
  Examples/TrussGenerator_2D/TrussGenerator.py
Labels: Small
