Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2023-01, with the labels that each got.

#213 DocumentCache added
  RFEM/BasicObjects/member.py
  RFEM/TimberDesign/__init__.py
  RFEM/TypesForTimberDesign/timberMemberRotationalRestraint.py
  RFEM/initModel.py
  UnitTests/test_aluminumMemberLocalSectionReduction.py
  UnitTests/test_loadCombination.py
  UnitTests/test_member.py
  UnitTests/test_timberServiceClass.py
Labels: Extra Small

#207 Heet ws example script
  Examples/SteelDesign/README.md
  Examples/SteelDesign/SteelDesignExcel.py
  Examples/SteelDesign/SteelDesignExcel.xlsm
  Examples/SteelDesign/SteelHall.py
  Examples/SteelDesign/img/xlwingsInterpreter.png
  Examples/SteelDesign/img/xlwingsRun.png
  RFEM/enums.py
Labels: Extra Large

#216 update
  Examples/SteelDesign/README.md
  Examples/SteelDesign/SteelDesignExcel.xlsm
Labels: Extra Small

#206 combination wizard
  RFEM/LoadCasesAndCombinations/combinationWizard.py
  RFEM/enums.py
  UnitTests/test_combinationWizard.py
Labels: Large

#205 USGS-RFEM6 Response Spectrum Link
  Examples/LinkUSGS/README.md
  Examples/LinkUSGS/UsgsRFEMLink.py
  Examples/LinkUSGS/access.py
  Examples/LinkUSGS/assets/logo_round.png
  RFEM/enums.py
Labels: Large
