Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2023-04, with the labels that each got.

#236 Add a parameter for ExportResultTablesToHtml()
  RFEM/Reports/html.py
Labels: Extra Small

#239 Knauer get functions
  RFEM/BasicObjects/line.py
  RFEM/BasicObjects/lineSet.py
  RFEM/BasicObjects/material.py
  RFEM/BasicObjects/member.py
  RFEM/BasicObjects/memberSet.py
  RFEM/BasicObjects/node.py
  RFEM/BasicObjects/opening.py
  RFEM/BasicObjects/section.py
  RFEM/BasicObjects/solid.py
  RFEM/BasicObjects/solidSet.py
  RFEM/BasicObjects/surface.py
  RFEM/BasicObjects/surfaceSet.py
  RFEM/BasicObjects/thickness.py
  UnitTests/test_basic_objects.py
Labels: Extra Large

#240 Heet load case
  RFEM/LoadCasesAndCombinations/loadCase.py
  UnitTests/test_LoadCases_Test.py
Labels: Small
