Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2023-03, with the labels that each got.

#228 Create test_saveFile.py
  UnitTests/test_saveFile.py
Labels: Extra Small

#232 Heet US-11521: Base Data
  RFEM/GuideObjects/note.py
  RFEM/baseData.py
  RFEM/enums.py
  UnitTests/test_baseData.py
  UnitTests/test_note.py
Labels: Large

#235 Types For Members Update
  RFEM/TypesForAluminumDesign/aluminumMemberRotationalRestraints.py
  RFEM/TypesForAluminumDesign/aluminumMemberShearPanel.py
  RFEM/TypesForMembers/memberRotationalRestraint.py
  RFEM/TypesForMembers/memberShearPanel.py
  RFEM/TypesForMembers/memberSupport.py
  RFEM/TypesForSteelDesign/steelMemberRotationalRestraints.py
  RFEM/TypesForSteelDesign/steelMemberShearPanel.py
  RFEM/TypesForTimberDesign/timberMemberRotationalRestraint.py
  RFEM/TypesForTimberDesign/timberMemberShearPanel.py
  RFEM/enums.py
  UnitTests/test_aluminumMemberRotationalRestraint.py
  UnitTests/test_aluminumMemberShearPanel.py
  UnitTests/test_memberRotationalRestraint.py
  UnitTests/test_memberShearPanel.py
  UnitTests/test_memberSupport.py
  UnitTests/test_steelMemberRotationalRestraint.py
  UnitTests/test_steelMemberShearPanel.py
  UnitTests/test_timberMemberRotationalRestraint.py
  UnitTests/test_timberMemberShearPanel.py
Labels: Extra Large
