Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2023-05, with the labels that each got.

#254 Result Combination Update
  RFEM/BasicObjects/thickness.py
  RFEM/Calculate/optimizationSettings.py
  RFEM/DynamicLoads/responseSpectrum.py
  RFEM/Imperfections/imperfectionCase.py
  RFEM/LoadCasesAndCombinations/loadCasesAndCombinations.py
  RFEM/LoadCasesAndCombinations/loadCombination.py
  RFEM/LoadCasesAndCombinations/resultCombination.py
  RFEM/Loads/freeLoad.py
  RFEM/Loads/lineLoad.py
  RFEM/Loads/linesetLoad.py
  RFEM/Loads/memberLoad.py
  RFEM/Loads/membersetload.py
  RFEM/Loads/surfaceLoad.py
  RFEM/Loads/surfacesetload.py
  RFEM/TypesForAluminumDesign/aluminumMemberTransverseWelds.py
  RFEM/TypesForLines/lineWeldedJoint.py
  RFEM/TypesForMembers/memberHinge.py
  RFEM/TypesForMembers/memberTransverseStiffeners.py
  RFEM/TypesForSpecialObjects/lineReleaseType.py
  RFEM/TypesForSpecialObjects/nodalReleaseType.py
  RFEM/TypesForSteelDesign/steelBoundaryConditions.py
  RFEM/TypesForSteelDesign/steelEffectiveLengths.py
  RFEM/TypesForTimberDesign/timberEffectiveLengths.py
  RFEM/TypesforConcreteDesign/ConcreteEffectiveLength.py
  RFEM/TypesforConcreteDesign/ConcreteSurfaceReinforcements.py
  RFEM/baseData.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/conftest.py
  UnitTests/test_ResultCombination.py
  UnitTests/test_loadCombination.py
  UnitTests/test_zCalculate.py
Labels: Extra Large

#253 Update Functionality of Result Tables
  RFEM/Results/resultTables.py
Labels: No Changes

#234 OndrejMichal: Script Generators
  .gitignore
  Examples/ScriptGenerator/README.md
  Examples/ScriptGenerator/WSScripGenerator.py
  Examples/ScriptGenerator/XMLScripGenerator.py
  RFEM/LoadCasesAndCombinations/modalAnalysisSettings.py
  RFEM/LoadCasesAndCombinations/spectralAnalysisSettings.py
  RFEM/TimberDesign/timberServiceLimitStateConfigurations.py
  RFEM/Tools/GetObjectNumbersByType.py
  RFEM/TypesForLines/lineHinge.py
  RFEM/baseSettings.py
  RFEM/dataTypes.py
  RFEM/enums.py
  UnitTests/test_GetAllObjects.py
  UnitTests/test_MembraneSurface_Test.py
  UnitTests/test_loadCasesAndCombinations.py
  UnitTests/test_loadCombination.py
Labels: Extra Large

#256 Bugfix ToDo: bug 24721_Line.NURBS()
  RFEM/BasicObjects/line.py
  UnitTests/test_basic_objects.py
Labels: Small

#257 MichalOndrej: Timber services and moisture
  RFEM/TypesForTimberDesign/timberMoistureClass.py
  RFEM/TypesForTimberDesign/timberServiceCondition.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/src/timberMoistureClass.rf6
  UnitTests/src/timberServiceConditionCSA.rf6
  UnitTests/src/timberServiceConditionGB.rf6
  UnitTests/src/timberServiceConditionNDS.rf6
  UnitTests/test_Reports.py
  UnitTests/test_timberMoistureClass.py
  UnitTests/test_timberServiceClass.py
  UnitTests/test_timberServiceConditionCSA.py
  UnitTests/test_timberServiceConditionGB.py
  UnitTests/test_timberServiceConditionNDS.py
Labels: Large

#258 Update to latest RFEM
  Examples/Cantilever/Demo1.py
  Examples/CantileverQt/Main.py
  Examples/RSectionExample/Demo_import_from_rsection.py
  Examples/SteelDesign/SteelDesignExcel.py
  Examples/SteelDesign/SteelHall.py
  Examples/main.py
  RFEM/BasicObjects/member.py
  RFEM/LoadCasesAndCombinations/loadCombination.py
  RFEM/LoadCasesAndCombinations/resultCombination.py
  RFEM/Loads/lineLoad.py
  RFEM/Loads/memberLoad.py
  RFEM/Loads/membersetload.py
  RFEM/Loads/nodalLoad.py
  RFEM/Loads/solidLoad.py
  RFEM/Results/resultTables.py
  RFEM/Tools/GetObjectNumbersByType.py
  RFEM/TypesForMembers/memberEccentricity.py
  RFEM/TypesForMembers/memberRotationalRestraint.py
  RFEM/TypesForMembers/memberShearPanel.py
  RFEM/TypesForMembers/memberSupport.py
  RFEM/TypesForSpecialObjects/nodalReleaseType.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/conftest.py
  UnitTests/test_GetAllObjects.py
  UnitTests/test_LineLoads_Test.py
  UnitTests/test_MemberLoad_test.py
  UnitTests/test_MemberSetLoad_test.py
  UnitTests/test_NodalLoad_test.py
  UnitTests/test_ResultCombination.py
  UnitTests/test_SectionDialogue.py
  UnitTests/test_SolidLoads.py
  UnitTests/test_aluminumMemberTransverseWeld.py
  UnitTests/test_combinationWizard.py
  UnitTests/test_concreteDesignConfig.py
  UnitTests/test_loads.py
  UnitTests/test_memberShearPanel.py
  UnitTests/test_memberSupport.py
  UnitTests/test_nodalReleaseType.py
  UnitTests/test_typesForMembers.py
  UnitTests/test_zCalculate.py
Labels: Large
