Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2023-02, with the labels that each got.

#215 christmann timber hall design example
  Examples/Timber_Design/timber_hall.py
Labels: Large

#218 Heet line releases
  RFEM/BasicObjects/member.py
  RFEM/SpecialObjects/lineRelease.py
  RFEM/SpecialObjects/lineReleaseType.py
  RFEM/enums.py
  UnitTests/test_LineRelease.py
  UnitTests/test_LineReleaseType.py
Labels: Extra Large

#222 thickness layer update
  RFEM/BasicObjects/thickness.py
  RFEM/enums.py
Labels: Small

#223 Update SteelDesignExcel.py
  Examples/SteelDesign/SteelDesignExcel.py
Labels: Extra Small

#214 Knauer windanalysis
  RFEM/BasicObjects/thickness.py
  RFEM/LoadCasesAndCombinations/windSimulationAnalysisSetting.py
  RFEM/enums.py
  UnitTests/test_windSimulationAnalysisSetting.py
Labels: Large

#225 Heet docstring update
  RFEM/BasicObjects/thickness.py
  RFEM/DynamicLoads/responseSpectrum.py
  RFEM/LoadCasesAndCombinations/combinationWizard.py
  RFEM/LoadCasesAndCombinations/loadCase.py
  RFEM/LoadCasesAndCombinations/windSimulationAnalysisSetting.py
  RFEM/SpecialObjects/lineRelease.py
  RFEM/SpecialObjects/lineReleaseType.py
  RFEM/SteelDesign/steelServiceabilityConfiguration.py
  RFEM/SteelDesign/steelUltimateConfigurations.py
  RFEM/TimberDesign/timberServiceLimitStateConfigurations.py
  RFEM/TimberDesign/timberUltimateConfigurations.py
  UnitTests/test_windSimulationAnalysisSetting.py
Labels: Medium
