Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2024-02, with the labels that each got.

#330 Heet aluminum design result table
  RFEM/Results/resultTables.py
  UnitTests/test_resultTableAluminumDesignAddOn.py
Labels: Large

#329 Rebecca calculate in cloud
  Examples/CalculateInCloudExample/CalculateInCloudExample.py
  Examples/CalculateInCloudExample/README.md
Labels: Extra Small

#332 Bugfix G-157811: WS Core - plausibility_check function returns OK even if there is problem
  Examples/ConcreteBridge/concrete_bridge.py
  Examples/SteelDesign/SteelDesignExcel.py
  Examples/SteelDesign/SteelHall.py
  Examples/Timber_Design/timber_hall.py
  RFEM/Tools/PlausibilityCheck.py
  RFEM/enums.py
  RFEM/initModel.py
  UnitTests/test_plausiblityCheck.py
Labels: Extra Small

#333 Origin/bug 165699
  .vscode/launch.json
  Examples/Cantilever/Demo1.py
  RFEM/initModel.py
  UnitTests/test_zCalculate.py
Labels: Small

#337 added parameter for unlock stiffness modif of thickness layers
  RFEM/BasicObjects/thickness.py
Labels: Extra Small

#331 Added function and test for UserDefinedMaterial
  RFEM/BasicObjects/coordinateSystem.py
  RFEM/BasicObjects/material.py
  RFEM/enums.py
  UnitTests/test_basic_objects.py
Labels: Large

#338 FE Mesh Tables
  RFEM/Results/meshTables.py
  UnitTests/test_MeshTables.py
Labels: Medium

#342 Rebecca bugfix line set load (LOAD_DISTRIBUTION_CONCENTRATED_VARYING
  RFEM/Loads/linesetLoad.py
Labels: Extra Small
