Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2024-01, with the labels that each got.

#317 Design Situation and Combination Wizard tests update
  UnitTests/test_DesignSituations.py
  UnitTests/test_steelEffectiveLengths.py
Labels: Medium

#319 Create CalculateInCloud function
  Examples/CalculateInCloudExample/CalculateInCloudExample.py
  Examples/CalculateInCloudExample/README.md
  RFEM/initModel.py
Labels: Extra Small

#324 BUG: Missing definition of modelLst in init.Model.py
  Examples/BasicExample/main.py
  Examples/BasicExample/window.py
  Examples/CantileverQt/Main.py
  Examples/LinkUSGS/UsgsRFEMLink.py
  Examples/LinkUSGS/access.py
  Examples/SteelDesign/SteelDesignExcel.py
  Examples/TankWebApp/tankWebApp.py
  Examples/TrussGenerator_2D/TrussGenerator.py
  RFEM/connectionGlobals.py
  RFEM/dependencies.py
  RFEM/initModel.py
Labels: Extra Small

#320 Action and Action Combination
  RFEM/LoadCasesAndCombinations/action.py
  RFEM/LoadCasesAndCombinations/actionCombination.py
  RFEM/enums.py
  UnitTests/test_Action.py
  UnitTests/test_ActionCombination.py
Labels: Large

#325 Heet aluminum design
  RFEM/AluminumDesign/__init__.py
  RFEM/AluminumDesign/aluminumSLSConfiguration.py
  RFEM/AluminumDesign/aluminumULSConfiguration.py
  UnitTests/test_aluminumDesignSLSConfiguration.py
  UnitTests/test_aluminumDesignULSConfigurations.py
Labels: Medium

#326 VasStach concrete bridge example
  Examples/ConcreteBridge/README.md
  Examples/ConcreteBridge/concrete_bridge.py
  Examples/ConcreteBridge/demo_image.png
Labels: Medium
