Repository Dlubal-Software/RFEM_Python_Client, pull requests merged in 2024-03, with the labels that each got.

#344 Fixed
  RFEM/BasicObjects/thickness.py
  UnitTests/test_Thickness_Test.py
Labels: Extra Small

#346 Update coordinateSystem.py
  RFEM/GuideObjects/coordinateSystem.py
  RFEM/Tools/GetObjectNumbersByType.py
  UnitTests/test_basic_objects.py
  UnitTests/test_guide_objects.py
Labels: Small

#345 Update initModel.py
  RFEM/initModel.py
Labels: Extra Small

#348 Heet docstring update
  RFEM/BasicObjects/material.py
  RFEM/GuideObjects/coordinateSystem.py
  RFEM/LoadCasesAndCombinations/action.py
  RFEM/LoadCasesAndCombinations/actionCombination.py
  RFEM/LoadCasesAndCombinations/resultCombination.py
  RFEM/LoadCasesAndCombinations/windSimulationAnalysisSetting.py
  RFEM/TypesForSolids/solidContact.py
Labels: Small

#349 Member defined by line number
  RFEM/BasicObjects/member.py
Labels: Medium

#352 Heet deformed mesh result
  RFEM/Results/meshTables.py
  UnitTests/test_LineLoads_Test.py
  UnitTests/test_MeshTables.py
Labels: Medium
